name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Check Prettier formatting
        run: npm run format:check
        
      - name: Run TypeScript type checking
        run: npm run typecheck
        
      - name: Run tests
        run: npm run test -- --coverage --watchAll=false
        
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: quality-gates
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: EAS Local Build (Preview)
        run: eas build --profile preview --platform all --local --no-wait
        env:
          EXPO_PUBLIC_API_URL: https://241runners-api-v2.azurewebsites.net
          
      - name: EAS Local Build (Production)
        run: eas build --profile production --platform all --local --no-wait
        env:
          EXPO_PUBLIC_API_URL: https://241runners-api-v2.azurewebsites.net
