name: Workflow Status

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Security Scan", "Code Quality"]
    types: [completed]

jobs:
  status:
    name: Update Status
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    
    steps:
    - name: Check workflow status
      run: |
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Status: ${{ github.event.workflow_run.conclusion }}"
        echo "Branch: ${{ github.event.workflow_run.head_branch }}"
        
    - name: Notify on failure
      if: github.event.workflow_run.conclusion == 'failure'
      run: |
        echo "❌ Workflow ${{ github.event.workflow_run.name }} failed!"
        echo "Please check the logs and fix any issues."
